### ISSUE TITLE
parallel version requirement?

### ISSUE THREAD

**Issue by peterdfields** [sreeramkannan/Shannon#8]
Just trying to run the sample data with the -p flag. I run into the following error:

parallel: Error: --tollef has been retired.
parallel: Error: Remove --tollef or use --gnu to override --tollef.

I've tried a couple different versions of parallel but some permutation of the above error always happens. Without the -p flag the sample datasets finish assembly as expected. The above error was generated with the install version of parallel = stable 20160122 installed via Linuxbrew onto an Ubuntu 14 machine.

**Comment by sreeramkannan** [comment]
Hi Peter,
Thanks very much for trying out Shannon, and for your feedback.Sorry for the delayed response.

 I could not quite figure out what the issue was with GNU parallel on your system, but decided, as a consequence to get rid of the dependency on Parallel. Shannon can now run in parallel mode without GNU parallel dependency (directly using python parallelization). Please try it out now and let me know if it solves your problem. Shannon also has been improved on multiple fronts, so look forward to hear back from you.
